core/ToDo/urls.py
from django.urls import path
from . import views

app_name = "ToDo"

urlpatterns = [
    path("",views.TaskList.as_view(),name="task-list"),
    path("create/",views.TaskCreate.as_view(),name="task-create"),
    path("update/<int:pk>/",views.TaskUpdate.as_view(),name="task-update"),
    path("delete/<int:pk>/",views.TaskDelete.as_view(),name="task-delete"),
    path("complate/<int:pk>/",views.TaskComplate.as_view(),name="task-complate"),
]

core/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.CustomLoginView.as_view(), name="login"),
    path("logout/", views.CustomLogoutView.as_view(next_page="/"), name="logout"),
    path("register/", views.RegisterView.as_view(), name="register"),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path("ToDo/", include("ToDo.urls", namespace="todo")),
]

core/ToDo/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length= 250 )
    complate = models.BooleanField(default= False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    
    class meta:
        order_with_respect_to = "user"

core/accounts/models.py
from django.db import models

# Create your models here.

core/ToDo/forms.py
from django import forms
from .models import Task

class TaskUpdateForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'complate'] 
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Title'}),
            'complate': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

core/ToDo/views.py
from django.shortcuts import render
from .models import Task
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView,CreateView,DeleteView
from django.urls import reverse_lazy
from ToDo.forms import TaskUpdateForm
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "todo/task_list.html"

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)
    
    
class TaskCreate(LoginRequiredMixin,CreateView):
    model = Task
    fields = ["title"]
    success_url = reverse_lazy("ToDo:task-list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)
    

class TaskDelete(LoginRequiredMixin,DeleteView):
    model = Task 
    template_name = 'todo/task_confirm_delete.html'
    success_url = reverse_lazy('ToDo:task-list')

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TaskUpdate(LoginRequiredMixin,UpdateView):
    model = Task
    success_url = reverse_lazy("ToDo:task-list")
    template_name = 'todo/task_update_form.html'
    form_class = TaskUpdateForm


class TaskComplate(LoginRequiredMixin,View):
    model = Task
    success_url = reverse_lazy("ToDo:task-list")

    def get(self, request, *args, **kwargs):
        object = Task.objects.get(id=kwargs.get("pk"))
        object.complate = True
        object.save()
        return redirect(self.success_url)




                                                   

core/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.views.generic.edit import FormView
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
from django.contrib.auth import login
from django.shortcuts import redirect
# Create your views here.

class CustomLoginView(LoginView):
    template_name = "accounts/login.html"
    fields = "username","password"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy("ToDo:task-list")
    

class CustomLogoutView(LogoutView):
    next_page = reverse_lazy("accounts:login.html")


class RegisterView(FormView):
    template_name = "accounts/register.html"
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("ToDo:task-list")

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterView, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("ToDo:task-list")
        return super(RegisterView, self).get(*args, **kwargs)

core/ToDo/templates/todo/base.html
<!doctype html>
<html lang="en">

<head>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ali Bigdeli">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <style>
        body {
            width: 100%;
            height: 100vh;            
            background: linear-gradient(to bottom, #e6e6e6 0%, #ffffff 100%);
        }
    </style>
    {% block extra_css %}{% endblock %}
</head>

<body>
    {% block content %}{% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock %}
</body>

</html>

core/ToDo/templates/todo/task_confirm_delete.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Delete Task{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-5 shadow">
            <div class="modal-header p-5 pb-4 border-bottom-0">
                <h2 class="fw-bold mb-0 text-danger">Delete Task</h2>
                <a class="btn-close" href="{% url 'ToDo:task-list' %}"></a>
            </div>
            <div class="modal-body p-5 pt-0">
                <form method="POST" action="">
                    {% csrf_token %}
                    <p class="fs-5">Are you sure you want to delete "<strong>{{ object }}</strong>"?</p>

                    <div class="d-flex gap-2 mt-4">
                        <button type="submit" class="btn btn-danger w-50">Confirm</button>
                        <a href="{% url 'ToDo:task-list' %}" class="btn btn-secondary w-50">Cancel</a>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}

core/ToDo/templates/todo/task_form.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Create Task{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-5 shadow">
            <div class="modal-header p-5 pb-4 border-bottom-0">
                <h2 class="fw-bold mb-0">Add New Task</h2>
                <a class="btn-close" href="{% url 'ToDo:task-list' %}"></a>
            </div>
            <div class="modal-body p-5 pt-0">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        <input 
                            type="text" 
                            name="{{ form.title.name }}" 
                            value="{{ form.title.value }}" 
                            class="form-control" 
                            id="titleInput" 
                            placeholder="Title"
                        >
                        <label for="titleInput">Title</label>
                    </div>
                    <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">
                        Create Task
                    </button>
                    <a href="{% url 'ToDo:task-list' %}" class="btn btn-secondary w-100">Cancel</a>
                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}

core/ToDo/templates/todo/task_list.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %} Todo List {% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-5 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <h2 class="fw-bold mb-0">Todo App</h2>
         {% if request.user.is_authenticated %}
  <form method="POST" action="{% url 'accounts:logout' %}">
    {% csrf_token %}
    <button class="btn btn-outline-danger btn-sm">
      Logout
    </button>
  </form>
  {% endif %}
      </div>
      <div class="modal-body p-5 pt-0">
        <form class="pt-3" method="POST" action="{% url 'ToDo:task-create' %}">
          {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" class="form-control rounded-4" name="title" placeholder="Enter task title"
              aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary" type="submit">Add</button>
          </div>
          <hr class="my-4">
     {% for task in tasks %}
<div class="input-group py-1">
    <span type="text" class="form-control" aria-label="Text input with segmented dropdown button">
        {{ task.title }}
        {% if task.complate %}
            <i class="bi bi-check-circle-fill text-success ms-2"></i>
        {% endif %}
    </span>
    <a type="button" class="btn btn-danger" href="{% url 'ToDo:task-delete' task.id %}"><i class="bi bi-trash"></i></a>
    <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="visually-hidden">Toggle Dropdown</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end">
        <li><a class="dropdown-item" href="{% url 'ToDo:task-complate' task.id %}">Done</a></li>
        <li><a class="dropdown-item" href="{% url 'ToDo:task-update' task.id %}">Edit</a></li>
    </ul>
</div>
{% endfor %}
     
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

core/ToDo/templates/todo/task_update_form.html
{% extends 'todo/base.html' %}
{% load static %}

{% block title %}Edit Task{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block py-5" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content rounded-5 shadow">
            <div class="modal-header p-5 pb-4 border-bottom-0">
                <h2 class="fw-bold mb-0">Edit Task</h2>
                <a class="btn-close" href="{% url 'ToDo:task-list' %}"></a>
            </div>
            <div class="modal-body p-5 pt-0">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="form-floating mb-3">
                        {{ form.title }}
                        <label for="{{ form.title.id_for_label }}">Title</label>
                    </div>
                    <div class="form-check mb-3">
                        {{ form.complate }}
                        <label class="form-check-label" for="{{ form.complate.id_for_label }}">
                            Complete
                        </label>
                    </div>
                    <button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">
                        Save Changes
                    </button>
                    <a href="{% url 'ToDo:task-list' %}" class="btn btn-secondary w-100">Cancel</a>
                </form>
            </div>

        </div>
    </div>
</div>
{% endblock %}

core/accounts/templates/accounts/login.html
{% extends 'todo/base.html' %}

{% block title %}Login{% endblock %}

{% block extra_css %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        user-select: none;
    }
</style>
<link href="https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}

{% block content %}
<main class="form-signin text-center">

    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}

        <img class="mb-4 rounded-circle shadow-sm"
             src="https://icc-aria.ir/static/img/team_11.jpg"
             alt="User Avatar"
             width="140" height="140">

        <h1 class="h4 mb-3 fw-normal">Sign in to your account</h1>

        <div class="form-floating mb-2">
            <input type="text"
                   name="username"
                   class="form-control"
                   id="floatingInput"
                   placeholder="Username"
                   autofocus
                   required>
            <label for="floatingInput">Username</label>
        </div>

        <div class="form-floating mb-3">
            <input type="password"
                   name="password"
                   class="form-control"
                   id="floatingPassword"
                   placeholder="Password"
                   required>
            <label for="floatingPassword">Password</label>
        </div>

        <button class="w-100 btn btn-lg btn-primary" type="submit">
            Sign In
        </button>

        <p class="mt-3 mb-0">
            Don’t have an account?
            <a href="{% url 'accounts:register' %}">Create one</a>
        </p>

        <p class="mt-4 text-muted small">&copy; 2024</p>
    </form>

    {% if form.errors %}
    <div class="alert alert-danger mt-3 text-start">
        <strong>Login failed:</strong>
        <ul class="mb-0">
            {% for field in form %}
                {% for error in field.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

</main>
{% endblock %}

core/accounts/templates/accounts/register.html
{% extends 'todo/base.html' %}

{% block title %} Register {% endblock %}

{% block extra_css %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>
<link href="https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}

{% block content %}
<main class="form-signin text-center">
    <form method="POST" action="{% url 'accounts:register' %}">
        {% csrf_token %}

        <img class="mb-4 rounded-circle shadow p-1"
             src="https://icc-aria.ir/static/img/team_11.jpg"
             width="120" height="120" alt="avatar">

        <h1 class="h3 mb-3 fw-normal">Create Account</h1>

        <div class="form-floating mb-2">
            <input type="text"
                   name="username"
                   class="form-control"
                   id="id_username"
                   placeholder="Username"
                   required>
            <label for="id_username">Username</label>
        </div>

        <div class="form-floating mb-2">
            <input type="password"
                   name="password1"
                   class="form-control"
                   id="id_password1"
                   placeholder="Password"
                   autocomplete="new-password"
                   required>
            <label for="id_password1">Password</label>
        </div>

        <div class="form-floating mb-3">
            <input type="password"
                   name="password2"
                   class="form-control"
                   id="id_password2"
                   placeholder="Repeat Password"
                   autocomplete="new-password"
                   required>
            <label for="id_password2">Repeat Password</label>
        </div>

        <button class="w-100 btn btn-lg btn-primary" type="submit">
            Register
        </button>

        <p class="mt-3">
            Already have an account?
            <a href="{% url 'accounts:login' %}">Login</a>
        </p>

        {% if form.errors %}
        <div class="alert alert-danger text-start mt-3">
            <strong>Please fix the errors below:</strong>
            <ul class="mb-0">
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}

        <p class="mt-4 text-muted">&copy; 2025</p>
    </form>
</main>
{% endblock %}